# Generated by Django 4.1.1 on 2023-01-16 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField(blank=True, default=20)),
                ('sold', models.IntegerField(blank=True, default=0)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
